#include "graphics/RIVK.h"

#if DEVICE_IMPL_VULKAN

const VkFormat RIFormatToVK(uint32_t format) {
	switch (format) {
		case RI_FORMAT_UNKNOWN: return VK_FORMAT_UNDEFINED;
		case RI_FORMAT_L8_A8_UNORM: return VK_FORMAT_R8G8_UNORM;
		case RI_FORMAT_L8_UNORM: return VK_FORMAT_R8_UNORM;
		case RI_FORMAT_A8_UNORM: return VK_FORMAT_R8_UNORM;
		case RI_FORMAT_D16_UNORM_S8_UINT: return VK_FORMAT_D16_UNORM_S8_UINT;
		case RI_FORMAT_D24_UNORM_S8_UINT: return VK_FORMAT_D24_UNORM_S8_UINT;
		case RI_FORMAT_D32_SFLOAT_S8_UINT: return VK_FORMAT_D32_SFLOAT_S8_UINT;
		case RI_FORMAT_R8_UNORM: return VK_FORMAT_R8_UNORM;
		case RI_FORMAT_R8_SNORM: return VK_FORMAT_R8_SNORM;
		case RI_FORMAT_R8_UINT: return VK_FORMAT_R8_UINT;
		case RI_FORMAT_R8_SINT: return VK_FORMAT_R8_SINT;
		case RI_FORMAT_RG8_UNORM: return VK_FORMAT_R8G8_UNORM;
		case RI_FORMAT_RG8_SNORM: return VK_FORMAT_R8G8_SNORM;
		case RI_FORMAT_RG8_UINT: return VK_FORMAT_R8G8_UINT;
		case RI_FORMAT_RG8_SINT: return VK_FORMAT_R8G8_SINT;
		case RI_FORMAT_BGRA8_UNORM: return VK_FORMAT_B8G8R8A8_UNORM;
		case RI_FORMAT_BGRA8_SRGB: return VK_FORMAT_B8G8R8A8_SRGB;
		case RI_FORMAT_BGR8_UNORM: return VK_FORMAT_B8G8R8_UNORM;
		case RI_FORMAT_RGB8_UNORM: return VK_FORMAT_R8G8B8_UNORM;
		case RI_FORMAT_RGBA8_UNORM: return VK_FORMAT_R8G8B8A8_UNORM;
		case RI_FORMAT_RGBA8_SNORM: return VK_FORMAT_R8G8B8A8_SNORM;
		case RI_FORMAT_RGBA8_UINT: return VK_FORMAT_R8G8B8A8_UINT;
		case RI_FORMAT_RGBA8_SINT: return VK_FORMAT_R8G8B8A8_SINT;
		case RI_FORMAT_RGBA8_SRGB: return VK_FORMAT_R8G8B8A8_SRGB;
		case RI_FORMAT_R16_UNORM: return VK_FORMAT_R16_UNORM;
		case RI_FORMAT_R16_SNORM: return VK_FORMAT_R16_SNORM;
		case RI_FORMAT_R16_UINT: return VK_FORMAT_R16_UINT;
		case RI_FORMAT_R16_SINT: return VK_FORMAT_R16_SINT;
		case RI_FORMAT_R16_SFLOAT: return VK_FORMAT_R16_SFLOAT;
		case RI_FORMAT_RG16_UNORM: return VK_FORMAT_R16G16_UNORM;
		case RI_FORMAT_RG16_SNORM: return VK_FORMAT_R16G16_SNORM;
		case RI_FORMAT_RG16_UINT: return VK_FORMAT_R16G16_UINT;
		case RI_FORMAT_RG16_SINT: return VK_FORMAT_R16G16_SINT;
		case RI_FORMAT_RG16_SFLOAT: return VK_FORMAT_R16G16_SFLOAT;
		case RI_FORMAT_RGBA16_UNORM: return VK_FORMAT_R16G16B16A16_UNORM;
		case RI_FORMAT_RGBA16_SNORM: return VK_FORMAT_R16G16B16A16_SNORM;
		case RI_FORMAT_RGBA16_UINT: return VK_FORMAT_R16G16B16A16_UINT;
		case RI_FORMAT_RGBA16_SINT: return VK_FORMAT_R16G16B16A16_SINT;
		case RI_FORMAT_RGBA16_SFLOAT: return VK_FORMAT_R16G16B16A16_SFLOAT;
		case RI_FORMAT_R32_UINT: return VK_FORMAT_R32_UINT;
		case RI_FORMAT_R32_SINT: return VK_FORMAT_R32_SINT;
		case RI_FORMAT_R32_SFLOAT: return VK_FORMAT_R32_SFLOAT;
		case RI_FORMAT_RG32_UINT: return VK_FORMAT_R32G32_UINT;
		case RI_FORMAT_RG32_SINT: return VK_FORMAT_R32G32_SINT;
		case RI_FORMAT_RG32_SFLOAT: return VK_FORMAT_R32G32_SFLOAT;
		case RI_FORMAT_RGB32_UINT: return VK_FORMAT_R32G32B32_UINT;
		case RI_FORMAT_RGB32_SINT: return VK_FORMAT_R32G32B32_SINT;
		case RI_FORMAT_RGB32_SFLOAT: return VK_FORMAT_R32G32B32_SFLOAT;
		case RI_FORMAT_RGBA32_UINT: return VK_FORMAT_R32G32B32A32_UINT;
		case RI_FORMAT_RGBA32_SINT: return VK_FORMAT_R32G32B32A32_SINT;
		case RI_FORMAT_RGBA32_SFLOAT: return VK_FORMAT_R32G32B32A32_SFLOAT;
		case RI_FORMAT_R10_G10_B10_A2_UNORM: return VK_FORMAT_A2R10G10B10_UNORM_PACK32;
		case RI_FORMAT_R10_G10_B10_A2_UINT: return VK_FORMAT_A2R10G10B10_UINT_PACK32;
		case RI_FORMAT_R11_G11_B10_UFLOAT: return VK_FORMAT_B10G11R11_UFLOAT_PACK32;
		case RI_FORMAT_R9_G9_B9_E5_UNORM: return VK_FORMAT_E5B9G9R9_UFLOAT_PACK32;
		case RI_FORMAT_R5_G6_B5_UNORM: return VK_FORMAT_R5G6B5_UNORM_PACK16;
		case RI_FORMAT_R5_G5_B5_A1_UNORM: return VK_FORMAT_A1R5G5B5_UNORM_PACK16;
		case RI_FORMAT_R4_G4_B4_A4_UNORM: return VK_FORMAT_R4G4B4A4_UNORM_PACK16;
		case RI_FORMAT_BC1_RGBA_UNORM: return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
		case RI_FORMAT_BC1_RGBA_SRGB: return VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
		case RI_FORMAT_BC2_RGBA_UNORM: return VK_FORMAT_BC2_UNORM_BLOCK;
		case RI_FORMAT_BC2_RGBA_SRGB: return VK_FORMAT_BC2_SRGB_BLOCK;
		case RI_FORMAT_BC3_RGBA_UNORM: return VK_FORMAT_BC3_UNORM_BLOCK;
		case RI_FORMAT_BC3_RGBA_SRGB: return VK_FORMAT_BC3_SRGB_BLOCK;
		case RI_FORMAT_BC4_R_UNORM: return VK_FORMAT_BC4_UNORM_BLOCK;
		case RI_FORMAT_BC4_R_SNORM: return VK_FORMAT_BC4_SNORM_BLOCK;
		case RI_FORMAT_BC5_RG_UNORM: return VK_FORMAT_BC5_UNORM_BLOCK;
		case RI_FORMAT_BC5_RG_SNORM: return VK_FORMAT_BC5_SNORM_BLOCK;
		case RI_FORMAT_BC6H_RGB_UFLOAT: return VK_FORMAT_BC6H_UFLOAT_BLOCK;
		case RI_FORMAT_BC6H_RGB_SFLOAT: return VK_FORMAT_BC6H_SFLOAT_BLOCK;
		case RI_FORMAT_BC7_RGBA_UNORM: return VK_FORMAT_BC7_UNORM_BLOCK;
		case RI_FORMAT_BC7_RGBA_SRGB: return VK_FORMAT_BC7_SRGB_BLOCK;
		case RI_FORMAT_D16_UNORM: return VK_FORMAT_D16_UNORM;
		case RI_FORMAT_D32_SFLOAT: return VK_FORMAT_D32_SFLOAT;
		case RI_FORMAT_D32_SFLOAT_S8_UINT_X24: return VK_FORMAT_D32_SFLOAT_S8_UINT;
		case RI_FORMAT_R24_UNORM_X8: return VK_FORMAT_X8_D24_UNORM_PACK32;
		case RI_FORMAT_X24_R8_UINT: return VK_FORMAT_X8_D24_UNORM_PACK32;
		case RI_FORMAT_X32_R8_UINT_X24: return VK_FORMAT_D32_SFLOAT_S8_UINT;
		case RI_FORMAT_R32_SFLOAT_X8_X24: return VK_FORMAT_D32_SFLOAT_S8_UINT;
		case RI_FORMAT_ETC1_R8G8B8_OES: return VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8_UNORM: return VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8_SRGB: return VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8A1_UNORM: return VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8A1_SRGB: return VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8A8_UNORM: return VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK;
		case RI_FORMAT_ETC2_R8G8B8A8_SRGB: return VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK;
		case RI_FORMAT_ETC2_EAC_R11_UNORM: return VK_FORMAT_EAC_R11_UNORM_BLOCK;
		case RI_FORMAT_ETC2_EAC_R11_SNORM: return VK_FORMAT_EAC_R11_SNORM_BLOCK;
		case RI_FORMAT_ETC2_EAC_R11G11_UNORM: return VK_FORMAT_EAC_R11G11_UNORM_BLOCK;
		case RI_FORMAT_ETC2_EAC_R11G11_SNORM: return VK_FORMAT_EAC_R11G11_SNORM_BLOCK;
		default: {
			const struct RIFormatProps* fmt =  GetRIFormatProps(format);
			hpl::FatalError("Unhandled RI_Format to VK %s!\n", fmt->name);
			break;
		}
	}
	return VK_FORMAT_UNDEFINED;
}


const enum RI_Format_e VKToRIFormat(VkFormat format) {
switch (format) {
		case VK_FORMAT_UNDEFINED: return  RI_FORMAT_UNKNOWN;
		case VK_FORMAT_R8G8_UNORM: return  RI_FORMAT_L8_A8_UNORM;
		case VK_FORMAT_R8_UNORM: return  RI_FORMAT_A8_UNORM;
		case VK_FORMAT_D16_UNORM_S8_UINT: return  RI_FORMAT_D16_UNORM_S8_UINT;
		case VK_FORMAT_D24_UNORM_S8_UINT: return  RI_FORMAT_D24_UNORM_S8_UINT;
		case VK_FORMAT_D32_SFLOAT_S8_UINT: return  RI_FORMAT_D32_SFLOAT_S8_UINT;
		case VK_FORMAT_R8_SNORM: return  RI_FORMAT_R8_SNORM;
		case VK_FORMAT_R8_UINT: return  RI_FORMAT_R8_UINT;
		case VK_FORMAT_R8_SINT: return  RI_FORMAT_R8_SINT;
		case VK_FORMAT_R8G8_SNORM: return  RI_FORMAT_RG8_SNORM;
		case VK_FORMAT_R8G8_UINT: return  RI_FORMAT_RG8_UINT;
		case VK_FORMAT_R8G8_SINT: return  RI_FORMAT_RG8_SINT;
		case VK_FORMAT_B8G8R8A8_UNORM: return  RI_FORMAT_BGRA8_UNORM;
		case VK_FORMAT_B8G8R8A8_SRGB: return  RI_FORMAT_BGRA8_SRGB;
		case VK_FORMAT_B8G8R8_UNORM: return  RI_FORMAT_BGR8_UNORM;
		case VK_FORMAT_R8G8B8_UNORM: return  RI_FORMAT_RGB8_UNORM;
		case VK_FORMAT_R8G8B8A8_UNORM: return  RI_FORMAT_RGBA8_UNORM;
		case VK_FORMAT_R8G8B8A8_SNORM: return  RI_FORMAT_RGBA8_SNORM;
		case VK_FORMAT_R8G8B8A8_UINT: return  RI_FORMAT_RGBA8_UINT;
		case VK_FORMAT_R8G8B8A8_SINT: return  RI_FORMAT_RGBA8_SINT;
		case VK_FORMAT_R8G8B8A8_SRGB: return  RI_FORMAT_RGBA8_SRGB;
		case VK_FORMAT_R16_UNORM: return  RI_FORMAT_R16_UNORM;
		case VK_FORMAT_R16_SNORM: return  RI_FORMAT_R16_SNORM;
		case VK_FORMAT_R16_UINT: return  RI_FORMAT_R16_UINT;
		case VK_FORMAT_R16_SINT: return  RI_FORMAT_R16_SINT;
		case VK_FORMAT_R16_SFLOAT: return  RI_FORMAT_R16_SFLOAT;
		case VK_FORMAT_R16G16_UNORM: return  RI_FORMAT_RG16_UNORM;
		case VK_FORMAT_R16G16_SNORM: return  RI_FORMAT_RG16_SNORM;
		case VK_FORMAT_R16G16_UINT: return  RI_FORMAT_RG16_UINT;
		case VK_FORMAT_R16G16_SINT: return  RI_FORMAT_RG16_SINT;
		case VK_FORMAT_R16G16_SFLOAT: return  RI_FORMAT_RG16_SFLOAT;
		case VK_FORMAT_R16G16B16A16_UNORM: return  RI_FORMAT_RGBA16_UNORM;
		case VK_FORMAT_R16G16B16A16_SNORM: return  RI_FORMAT_RGBA16_SNORM;
		case VK_FORMAT_R16G16B16A16_UINT: return  RI_FORMAT_RGBA16_UINT;
		case VK_FORMAT_R16G16B16A16_SINT: return  RI_FORMAT_RGBA16_SINT;
		case VK_FORMAT_R16G16B16A16_SFLOAT: return  RI_FORMAT_RGBA16_SFLOAT;
		case VK_FORMAT_R32_UINT: return  RI_FORMAT_R32_UINT;
		case VK_FORMAT_R32_SINT: return  RI_FORMAT_R32_SINT;
		case VK_FORMAT_R32_SFLOAT: return  RI_FORMAT_R32_SFLOAT;
		case VK_FORMAT_R32G32_UINT: return  RI_FORMAT_RG32_UINT;
		case VK_FORMAT_R32G32_SINT: return  RI_FORMAT_RG32_SINT;
		case VK_FORMAT_R32G32_SFLOAT: return  RI_FORMAT_RG32_SFLOAT;
		case VK_FORMAT_R32G32B32_UINT: return  RI_FORMAT_RGB32_UINT;
		case VK_FORMAT_R32G32B32_SINT: return  RI_FORMAT_RGB32_SINT;
		case VK_FORMAT_R32G32B32_SFLOAT: return  RI_FORMAT_RGB32_SFLOAT;
		case VK_FORMAT_R32G32B32A32_UINT: return  RI_FORMAT_RGBA32_UINT;
		case VK_FORMAT_R32G32B32A32_SINT: return  RI_FORMAT_RGBA32_SINT;
		case VK_FORMAT_R32G32B32A32_SFLOAT: return  RI_FORMAT_RGBA32_SFLOAT;
		case VK_FORMAT_A2R10G10B10_UNORM_PACK32: return  RI_FORMAT_R10_G10_B10_A2_UNORM;
		case VK_FORMAT_A2R10G10B10_UINT_PACK32: return  RI_FORMAT_R10_G10_B10_A2_UINT;
		// Swapchain surfaces on modern drivers commonly report the BGR-channel
		// variant A2B10G10R10 even when 8-bit surfaces are available; without
		// an explicit case it falls through to default and crashes
		// InitRISwapchain with a misleading error (the default branch indexes
		// riFormats[] by the raw VkFormat value, which happens to land on
		// "BC3_RGBA_SRGB" for VK_FORMAT_A2B10G10R10_UNORM_PACK32 = 64). Map to
		// the closest existing RI_Format slot; downstream renderers use this
		// only as a tag to pick a compatible render-target format.
		case VK_FORMAT_A2B10G10R10_UNORM_PACK32: return  RI_FORMAT_R10_G10_B10_A2_UNORM;
		case VK_FORMAT_A2B10G10R10_UINT_PACK32: return  RI_FORMAT_R10_G10_B10_A2_UINT;
		case VK_FORMAT_B10G11R11_UFLOAT_PACK32: return  RI_FORMAT_R11_G11_B10_UFLOAT;
		case VK_FORMAT_E5B9G9R9_UFLOAT_PACK32: return  RI_FORMAT_R9_G9_B9_E5_UNORM;
		case VK_FORMAT_R5G6B5_UNORM_PACK16: return  RI_FORMAT_R5_G6_B5_UNORM;
		case VK_FORMAT_A1R5G5B5_UNORM_PACK16: return  RI_FORMAT_R5_G5_B5_A1_UNORM;
		case VK_FORMAT_R4G4B4A4_UNORM_PACK16: return  RI_FORMAT_R4_G4_B4_A4_UNORM;
		case VK_FORMAT_BC1_RGBA_UNORM_BLOCK: return  RI_FORMAT_BC1_RGBA_UNORM;
		case VK_FORMAT_BC1_RGBA_SRGB_BLOCK: return  RI_FORMAT_BC1_RGBA_SRGB;
		case VK_FORMAT_BC2_UNORM_BLOCK: return  RI_FORMAT_BC2_RGBA_UNORM;
		case VK_FORMAT_BC2_SRGB_BLOCK: return  RI_FORMAT_BC2_RGBA_SRGB;
		case VK_FORMAT_BC3_UNORM_BLOCK: return  RI_FORMAT_BC3_RGBA_UNORM;
		case VK_FORMAT_BC3_SRGB_BLOCK: return  RI_FORMAT_BC3_RGBA_SRGB;
		case VK_FORMAT_BC4_UNORM_BLOCK: return  RI_FORMAT_BC4_R_UNORM;
		case VK_FORMAT_BC4_SNORM_BLOCK: return  RI_FORMAT_BC4_R_SNORM;
		case VK_FORMAT_BC5_UNORM_BLOCK: return  RI_FORMAT_BC5_RG_UNORM;
		case VK_FORMAT_BC5_SNORM_BLOCK: return  RI_FORMAT_BC5_RG_SNORM;
		case VK_FORMAT_BC6H_UFLOAT_BLOCK: return  RI_FORMAT_BC6H_RGB_UFLOAT;
		case VK_FORMAT_BC6H_SFLOAT_BLOCK: return  RI_FORMAT_BC6H_RGB_SFLOAT;
		case VK_FORMAT_BC7_UNORM_BLOCK: return  RI_FORMAT_BC7_RGBA_UNORM;
		case VK_FORMAT_BC7_SRGB_BLOCK: return  RI_FORMAT_BC7_RGBA_SRGB;
		case VK_FORMAT_D16_UNORM: return  RI_FORMAT_D16_UNORM;
		case VK_FORMAT_D32_SFLOAT: return  RI_FORMAT_D32_SFLOAT;
		// case VK_FORMAT_D32_SFLOAT_S8_UINT: return  RI_FORMAT_D32_SFLOAT_S8_UINT_X24;
		case VK_FORMAT_X8_D24_UNORM_PACK32: return  RI_FORMAT_R24_UNORM_X8;
		// case VK_FORMAT_X8_D24_UNORM_PACK32: return  RI_FORMAT_X24_R8_UINT;
		// case VK_FORMAT_D32_SFLOAT_S8_UINT: return  RI_FORMAT_X32_R8_UINT_X24;
		// case VK_FORMAT_D32_SFLOAT_S8_UINT: return  RI_FORMAT_R32_SFLOAT_X8_X24;
		case VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK: return  RI_FORMAT_ETC1_R8G8B8_OES;
		// case VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK: return  RI_FORMAT_ETC2_R8G8B8_UNORM;
		case VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK: return  RI_FORMAT_ETC2_R8G8B8_SRGB;
		case VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK: return  RI_FORMAT_ETC2_R8G8B8A1_UNORM;
		case VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK: return  RI_FORMAT_ETC2_R8G8B8A1_SRGB;
		case VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK: return  RI_FORMAT_ETC2_R8G8B8A8_UNORM;
		case VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK: return  RI_FORMAT_ETC2_R8G8B8A8_SRGB;
		case VK_FORMAT_EAC_R11_UNORM_BLOCK: return  RI_FORMAT_ETC2_EAC_R11_UNORM;
		case VK_FORMAT_EAC_R11_SNORM_BLOCK: return  RI_FORMAT_ETC2_EAC_R11_SNORM;
		case VK_FORMAT_EAC_R11G11_UNORM_BLOCK: return  RI_FORMAT_ETC2_EAC_R11G11_UNORM;
		case VK_FORMAT_EAC_R11G11_SNORM_BLOCK: return  RI_FORMAT_ETC2_EAC_R11G11_SNORM;
		default: {
			const struct RIFormatProps* fmt =  GetRIFormatProps(format);
			hpl::FatalError("Unhandled RI_Format to VK %s!\n", fmt->name);
			break;
		}
	}
	return RI_FORMAT_UNKNOWN;
}
#endif


