#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__

/* Normally generated by libogg's configure/cmake from config_types.h.in. The
   premake build compiles the ogg submodule from a manual source list (no
   configure step), so this portable, stdint-based copy stands in for the
   generated header. On Windows/MSVC os_types.h uses its own typedefs and never
   includes this file. The CMake build uses ogg's own CMakeLists, which
   generates the real header, so this copy is premake-only. */
#define INCLUDE_INTTYPES_H 1
#define INCLUDE_STDINT_H 1
#define INCLUDE_SYS_TYPES_H 1

#if INCLUDE_INTTYPES_H
#  include <inttypes.h>
#endif
#if INCLUDE_STDINT_H
#  include <stdint.h>
#endif
#if INCLUDE_SYS_TYPES_H
#  include <sys/types.h>
#endif

typedef int16_t ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t ogg_int64_t;
typedef uint64_t ogg_uint64_t;

#endif
