#version 460
#extension GL_GOOGLE_include_directive                   : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_debug_printf                            : enable
#extension GL_EXT_spirv_intrinsics                        : enable

#include "forward_shared.h"
#include "compress.glsl"
#include "bindless.resource.glsl"
#include "per_frame.resource.glsl"
#include "shaderUtils_surfel_cell.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= surfelCounter.aliveSurfelCnt) return;

    uint   surfelIndex   = surfelAlive[idx];
    Surfel surfel        = surfelBuffer[surfelIndex];
    vec3   camPos        = invViewMat[3].xyz;
    ivec4  cellPosIndex  = getCellPosNonUniform(surfel.position, camPos);

    for (uint i = 0; i < 27; ++i) {
        vec3  neighbourPos3 = cellPosIndex.xyz + neighborOffset[i];
        ivec4 neighbourPos  = ivec4(neighbourPos3, cellPosIndex.w);

        if (isSurfelIntersectCellNonUniform(surfel, neighbourPos, camPos)) {
            uint flattenIndex = getFlattenCellIndexNonUniform(neighbourPos);
            uint prevCount    = atomicAdd(cellBuffer[flattenIndex].surfelCount, 1);
            cellToSurfel[cellBuffer[flattenIndex].surfelOffset + prevCount] = surfelIndex;
        }
    }
}
