#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_spirv_intrinsics : enable

#include "host_device.h"
#include "bindless.resource.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint idx = gl_GlobalInvocationID.x;

	// Compute offset of the cell to surfel buffer
	// Cell Count
	if(idx >= kCellCount) return;

	// Get the cell to process
	CellInfo thisCell = cellBuffer[idx];
	if (thisCell.surfelCount == 0) return;

	//if(thisCell.surfelOffset != 0 &&  thisCell.surfelCount != 0) 
	//	debugPrintfEXT("surfelOffset:%d, surfelCount:%d\n", thisCell.surfelOffset, thisCell.surfelCount); 
	// Calculate offsets of the surfel buffer
	uint offset = atomicAdd(cellCounter.aliveSurfelInCell, thisCell.surfelCount);
	//if(idx == 40) debugPrintfEXT("surfelOffset:%d, surfelCount:%d\n", thisCell.surfelOffset, thisCell.surfelCount); 

	cellBuffer[idx].surfelOffset = offset;
	cellBuffer[idx].surfelCount = 0;
	
}
