#version 460
#extension GL_GOOGLE_include_directive                   : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "host_device.h"
#include "compress.glsl"
#include "bindless.resource.glsl"

#include "shaderUtils_surfel_cell.glsl"

// Compute input
layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint idx = gl_GlobalInvocationID.x;
	if (idx == 0)
	{
		surfelCounter.surfelRayCnt = 0;
		cellCounter.aliveSurfelInCell = 0;
	}
	//clear cellBuffer
	cellBuffer[idx].surfelCount = 0;
	cellBuffer[idx].surfelOffset = 0;
	// tmp value
	/*
	if (rtxState.frame > 1000)
	{
		surfelCounter.aliveSurfelCnt = 0;
		surfelCounter.deadSurfelCnt = kMaxSurfelCount;
		surfelDead[gl_GlobalInvocationID.x] = gl_GlobalInvocationID.x;
		surfelAlive[gl_GlobalInvocationID.x] = 0;
		Surfel surfel;
		surfel.position = vec3(0.0f);
		surfel.normal = 0;
		surfel.radius = 0.0f;
		surfel.radiance = vec3(0.0f);
		surfelBuffer[gl_GlobalInvocationID.x] = surfel;
	}*/

	/*
	surfelCounter.dirtySurfelCnt = surfelCounter.aliveSurfelCnt;
    if(idx < surfelCounter.aliveSurfelCnt) {
        surfelDirty[idx] = surfelAlive[idx];
    }*/

	// Reset alive surfel counter
}