#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "host_device.h"
#include "compress.glsl"
#include "random.glsl"
#include "bindless.resource.glsl"
#include "per_frame.resource.glsl"

#include "shaderUtils_surfel_cell.glsl"
#include "shaderUtils.glsl"

uint randSeed = 0;

void recycleSurfelInAlive(uint aliveArrayIndex) {
  uint surfelIndexToRecycle = surfelAlive[aliveArrayIndex];

  uint newAliveCnt = atomicAdd(surfelCounter.aliveSurfelCnt, -1) - 1;
  uint endSurfelIndex = surfelAlive[newAliveCnt];

  surfelAlive[aliveArrayIndex] = endSurfelIndex;

  uint newDeadIndex = kMaxSurfelCount - newAliveCnt - 1;
  surfelDead[newDeadIndex] = surfelIndexToRecycle;
}

bool shouldRecycleSurfel(in Surfel surfel, in SurfelRecycleInfo recycleInfo, in bool lastSeen, float surfelToCameraDistance) {

  // base check
  if (surfel.radius < 0.001 || recycleInfo.life == 0)
    return true;

  // if last seen, do not recycle
  if (lastSeen)
    return false;

  // Distance factor - recycle if too far
  float distanceFactor = smoothstep(50.0, 100.0, surfelToCameraDistance);

  // Life cycle factor
  float lifeFactor = (float(kMaxLife) - float(recycleInfo.life)) / float(kMaxLife);
  lifeFactor = pow(lifeFactor, 2.0);

  // Combine factors with weights
  float recycleProb = 0.1 * distanceFactor + 0.4 * lifeFactor;

  // Scale by surfel density
  float surfelCountFactor = float(surfelCounter.aliveSurfelCnt) / float(kMaxSurfelCount);
  surfelCountFactor *= step(0.8, surfelCountFactor);
  recycleProb *= surfelCountFactor;

  return rand(randSeed) < recycleProb;
}

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
  uint idx = gl_GlobalInvocationID.x;

  if (idx >= surfelCounter.aliveSurfelCnt) return;

  randSeed = tea(idx, totalFrames);

  uint surfelIndex = surfelAlive[idx];
  Surfel surfel = surfelBuffer[surfelIndex];
  surfel.radiance = surfel.msmeData.mean;

  float surfelRadius = surfel.radius;
  SurfelRecycleInfo recycleInfo = surfelRecycleInfo[surfelIndex];
  bool isSleeping = (recycleInfo.status & 0x0001u) != 0u;
  bool lastSeen = (recycleInfo.status & 0x0002u) != 0u;
  bool lastRefed = (recycleInfo.status & 0x0004u) != 0u;

  // Increase frame count
  recycleInfo.life = recycleInfo.life > 0u ? recycleInfo.life - 1u : 0u;
  recycleInfo.frame = uint(clamp(int(recycleInfo.frame) + 1, 0, 65535));

  // update sleep surfel life
  if (isSleeping && lastRefed)
    recycleInfo.life = kMaxLife / 2;

  if (lastSeen) {
    recycleInfo.life = kMaxLife;
    if (isSleeping) {
      isSleeping = false;
    }
  }

  float surfelToCameraDistance = distance(surfel.position, invViewMat[3].xyz);

  // Check if surfel valid
  if (!shouldRecycleSurfel(surfel, recycleInfo, lastSeen || lastRefed, surfelToCameraDistance)) {

    // Reset surfel radius
    float surfelToCameraDistance = distance(surfel.position, invViewMat[3].xyz);
    float fov = cameraFov;
    ivec2 imageRes = ivec2(viewportSize);
    vec2 resolution = vec2(imageRes.x, imageRes.y);

    float newRadius = calcSurfelRadius(surfelToCameraDistance, fov, resolution);
    float surfelMaxSize = getSurfelMaxSize(surfelToCameraDistance);
    if (isSleeping) {
      newRadius = min(newRadius, surfelMaxSize * 2.f);
    } else {
      newRadius = min(newRadius, surfelMaxSize);
    }

    if (lastSeen) newRadius = mix(surfel.radius, newRadius, 0.1f);
    newRadius = max(newRadius, surfelMaxSize * surfelMinSizeRatio);
    float radDiff = abs(surfel.radius - newRadius);
    surfel.msmeData.variance *= 1.0 + radDiff * 10.0;

    surfel.radius = newRadius;

    // Calculate number of surfels located at cell
    vec3 camPos = invViewMat[3].xyz;
    ivec4 cellPosIndex = getCellPosNonUniform(surfel.position, camPos);
    for (uint i = 0; i < 27; i++)
    {
      vec3 neighbourPos3 = cellPosIndex.xyz + neighborOffset[i];
      ivec4 neighbourPos = ivec4(neighbourPos3, cellPosIndex.w);

      if (isSurfelIntersectCellNonUniform(surfel, neighbourPos, camPos))
      {
        uint flattenIndex = getFlattenCellIndexNonUniform(neighbourPos);
        atomicAdd(cellBuffer[flattenIndex].surfelCount, 1);
      }
    }

    //Update ray information
    float variance = length(surfel.msmeData.variance);

    uint rayRequestCnt = uint(mix(4.0, 64.0, clamp(variance * 1.2, 0.f, 1.f)));

    if (isSleeping || !lastSeen) rayRequestCnt = rayRequestCnt / 4;
    if (recycleInfo.frame < 20) rayRequestCnt = 64;

    // allocate ray buffer
    uint rayOffset = atomicAdd(surfelCounter.surfelRayCnt, rayRequestCnt);
    if (rayOffset < kMaxRayCount)
    {
      surfel.rayOffset = rayOffset;
      surfel.rayCount = rayRequestCnt;

      SurfelRay initSurfelRay;
      initSurfelRay.surfelID = surfelIndex;

      for (uint rayIndex = 0; rayIndex < rayRequestCnt; ++rayIndex)
      {
        surfelRayBuffer[rayOffset + rayIndex] = initSurfelRay;
      }
    }
    else
    {
      atomicAdd(surfelCounter.surfelRayCnt, -rayRequestCnt);
    }

    // Update surfel
    surfelBuffer[surfelIndex] = surfel;
  }
  else
  {
    recycleSurfelInAlive(idx);
  }

  // reset lastSeen
  recycleInfo.status = isSleeping ? 0x0001 : 0x0000;
  // write back
  surfelRecycleInfo[surfelIndex] = recycleInfo;
}
